In [4]:
import numpy as np
a=np.array(5)
print("Print A= ",a)
b=np.array([1,2,3])
print("Print B= ", b)
addition= np.add(a,b)
print("After Addition =", addition)
sub=np.subtract(b,a)
print("After Subtraction =",sub)
mul=np.multiply (a,b)
print("After Multiplcation =",mul)
div=np.divide (b,a)
print("After Division =",div)
div1=np.divide (b,2)
print("After Division =",div1)

Print A=  5
Print B=  [1 2 3]
After Addition = [6 7 8]
After Subtraction = [-4 -3 -2]
After Multiplcation = [ 5 10 15]
After Division = [0.2 0.4 0.6]
After Division = [0.5 1.  1.5]


In [5]:
a= np.array([0.25,0.5,0.75,1])
print(a)
rec=np.reciprocal(a) 
print(rec)

[0.25 0.5  0.75 1.  ]
[4.         2.         1.33333333 1.        ]


In [6]:
a=np.array([5,10,1000])
print(a)
pow=np.power(a,2)
print("after ^2 = ", pow)
b=np.array([2,3,1])
pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)

[   5   10 1000]
after ^2 =  [     25     100 1000000]
after b array elements as ^ =  [  25 1000 1000]


In [16]:
a= np.array ([10,20,30])
b= np.array ([3,5,7])
print("values of A=", a)
print("values of B=", b)
mm=np.mod(a,b)
rm=np.remainder(a,b)
print("values of mod=", mm)
print("values of Remainder=", rm)

values of A= [10 20 30]
values of B= [3 5 7]
values of mod= [1 0 2]
values of Remainder= [1 0 2]


In [11]:
a=np.array([1.-2j, 8.+6j,7, 2+3j])
print(a)
print("real=",np.real(a))
print("imaginary=",np.imag(a))
print("Conjugate=", np.conj(a))

[1.-2.j 8.+6.j 7.+0.j 2.+3.j]
real= [1. 8. 7. 2.]
imaginary= [-2.  6.  0.  3.]
Conjugate= [1.+2.j 8.-6.j 7.-0.j 2.-3.j]


In [14]:
a=np.array ([10.9,5.4,987.98,2.56,25.5])
print(a)
print("after rounding up=", np.around(a))
print("after rounding up to 1st decimal value =", np.around(a,decimals=1))

[ 10.9    5.4  987.98   2.56  25.5 ]
after rounding up= [ 11.   5. 988.   3.  26.]
after rounding up to 1st decimal value = [ 10.9   5.4 988.    2.6  25.5]


In [15]:
a=np.array ([10.9,-5.5,987.98,-2.56,25.5])
print(a)
print('\n')
print(np.floor(a))
print(np.ceil(a))

[ 10.9   -5.5  987.98  -2.56  25.5 ]


[ 10.  -6. 987.  -3.  25.]
[ 11.  -5. 988.  -2.  26.]
