In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x) 

(array([3, 5, 6], dtype=int64),)


In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x) 

(array([1, 3, 5, 7], dtype=int64),)


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x) 

(array([0, 2, 4, 6], dtype=int64),)


In [7]:
import numpy as np
arr = np.array([6, 7, 18, 19])
x = np.searchsorted(arr,11)
print(x) 

2


In [9]:
import numpy as np
arr = np.array([6, 7, 18, 29])
x = np.searchsorted(arr, 19, side='right')
print(x) 

3


In [10]:
import numpy as np
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x) 

[1 2 3]
